// This file will be auto-generated by the Supabase CLI
// Run: supabase gen types typescript --project-id YOUR_PROJECT_ID --schema public > types/supabase.ts

export interface Database {
    public: {
        Tables: {
            user: {
                Row: {
                    id: string
                    email: string
                    name: string
                    avatar_url: string | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    email: string
                    name: string
                    avatar_url?: string | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    name?: string
                    avatar_url?: string | null
                    created_at?: string
                    updated_at?: string
                }
            }
            documents: {
                Row: {
                    id: string
                    title: string
                    content: string
                    author_id: string
                    visibility: 'public' | 'link_only' | 'password_protected' | 'private'
                    password_hash: string | null
                    access_token: string | null
                    created_at: string
                    updated_at: string
                    version: number
                }
                Insert: {
                    id?: string
                    title: string
                    content: string
                    author_id: string
                    visibility?: 'public' | 'link_only' | 'password_protected' | 'private'
                    password_hash?: string | null
                    access_token?: string | null
                    created_at?: string
                    updated_at?: string
                    version?: number
                }
                Update: {
                    id?: string
                    title?: string
                    content?: string
                    author_id?: string
                    visibility?: 'public' | 'link_only' | 'password_protected' | 'private'
                    password_hash?: string | null
                    access_token?: string | null
                    created_at?: string
                    updated_at?: string
                    version?: number
                }
            }
            document_collaborators: {
                Row: {
                    id: string
                    document_id: string
                    user_id: string
                    permission: 'read' | 'write' | 'admin'
                    created_at: string
                }
                Insert: {
                    id?: string
                    document_id: string
                    user_id: string
                    permission: 'read' | 'write' | 'admin'
                    created_at?: string
                }
                Update: {
                    id?: string
                    document_id?: string
                    user_id?: string
                    permission?: 'read' | 'write' | 'admin'
                    created_at?: string
                }
            }
            comments: {
                Row: {
                    id: string
                    document_id: string
                    user_id: string
                    content: string
                    parent_comment_id: string | null
                    position: any | null
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    document_id: string
                    user_id: string
                    content: string
                    parent_comment_id?: string | null
                    position?: any | null
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    document_id?: string
                    user_id?: string
                    content?: string
                    parent_comment_id?: string | null
                    position?: any | null
                    created_at?: string
                    updated_at?: string
                }
            }
            document_versions: {
                Row: {
                    id: string
                    document_id: string
                    content: string
                    version_number: number
                    created_by: string
                    created_at: string
                }
                Insert: {
                    id?: string
                    document_id: string
                    content: string
                    version_number: number
                    created_by: string
                    created_at?: string
                }
                Update: {
                    id?: string
                    document_id?: string
                    content?: string
                    version_number?: number
                    created_by?: string
                    created_at?: string
                }
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            [_ in never]: never
        }
        CompositeTypes: {
            [_ in never]: never
        }
    }
}
